### ISSUE TITLE
hccc-web setup not working ..

### ISSUE THREAD

**Issue by reksomu371** [hcccecit/hccc-web#72]
Tried to setup hccc-web, getting below error. 
Could you please re-visit the steps for setup.

Soma-MacBook-Pro:hccc-web-master somashekar$ npm install
npm WARN @angular/animations@6.0.5 requires a peer of @angular/core@6.0.5 but none is installed. You must install peer dependencies yourself.

audited 23486 packages in 11.258s
found 15 vulnerabilities (1 low, 10 moderate, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by hcccecit** [comment]
@reksomu371 these warnings can be ignored at this time.
